### ISSUE TITLE
Can bin/cgi-bin/faq.pl be removed ?

### ISSUE THREAD

**Issue by bschmalhofer** [RotherOSS/FAQ#15]
In normal installations, that is when using _otobo.psgi_, the path _faq.pl_ is no longer supported.  It is only a redirect to public.pl?Action=PublicFAQExplorer . Is it OK when **otobo/faq.pl** no longer is available? In this case the script should be removed.

**Comment by svenoe** [comment]
I wasn't even aware of it. Let's remove it, as it doesn't work at the moment, anyways.

Maybe we should provide an easy way to define redirects like that in otobo.psgi - via the SysConfig? Anyways this is a topic for otobo itself then.

**Comment by bschmalhofer** [comment]
I*m a bit hesitant to allow OTOBO packages to define their own pathes and scripts. If somebody really wants a redirect that it can be implemented with some JavaScript in _index.html_ or _404.html_ . But, as said above, this is a different discussion.

**Comment by bschmalhofer** [comment]
The scripts are removed. Closing this issue.
