### ISSUE TITLE
Issue with FAQ Link in AgentTicketCompose After Update to Version 11.0.6

### ISSUE THREAD

**Issue by KhalilHamada-OTOBO** [RotherOSS/FAQ#31]
In version 11.0.6, the FAQ link can be inserted in the agent portal while replying in "AgentTicketCompose", however, this action deletes and replaces the entire message.

**Comment by stefanhaerter** [comment]
Confirmed. Does not affect 10.1.

**Comment by stefanhaerter** [comment]
The problem here is that inserting into CKEditor 5 works differently than for CKEditor 4. In the responsible javascript code, the FAQ content is present as plain html string, but I have not yet found a way to insert html into the editor.
